version: '3.8'
services:
  client:
    build:
      context: ./frontend/ui-ux
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
  server:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - client