const express = require('express');
const router = express.Router();
const controller = require('../controllers/controller');


// router.post('/transcript', interviewController.addTranscriptLine);
// {
//     "interviewId": {uuid: generated by createInterview},
//     "question": {String: question asked by AI},
//     "answer": {String: answer given by user}
// }
// router.get('/transcript', interviewController.getTranscript);
// {
// }

module.exports = router;